---
# handlers file for ansible-airflow
#
- name: init airflow db
  shell: "{{airflow_cmd}} initdb"
  register: airflow_db_init_status
  until: airflow_db_init_status.rc == 0
  retries: 15
  delay: 5
  ignore_errors: yes
  environment:
    AIRFLOW_HOME: "{{airflow_home}}"
    PATH: "{{airflow_virtual_env_bin_path}}:{{ansible_env.PATH}}"

- name: wait for init airflow db
  wait_for: port={{airflow_webserver_port}} state=started

- name: update airflow pools info
  fail: msg="This handler not defined"

- name: update airflow users info
  fail: msg="This handler not defined"

- name: update airflow connections info
  fail: msg="This handler not defined"

- name: update airflow variables info
  command: "{% set kv = item.strip().split(';') %} {{airflow_cmd}} variables -s {{kv[0]}} {{kv[1]}}"
  with_lines: "cat {{airflow_variables_file}}"
  when: airflow_variables_file is defined and airflow_variables_file is not none

  
- name: restart airflow webserver
  supervisorctl:
    name: airflow_webserver 
    state: restarted

- name: restart airflow scheduler
  supervisorctl:
    name: airflow_scheduler
    state: restarted

- name: restart airflow all service
  supervisorctl:
    name: 'airflow:'
    state: restarted


